### Create a new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "binth4@hocmai.com",
  "password": "Hocmai@12345"
}

### App Sign iN

POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "binth2@hocmai.com",
  "password": "Hocmai@12345"
}

### Find user

GET http://localhost:3000/auth/1

### get the currently signed user

GET http://localhost:3000/auth/whoami

### SIGN Out

POST http://localhost:3000/auth/signout

### Find all users with a given email

GET http://localhost:3000/auth/?email=binth@hocmai.com

### Update user by id

PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "tahoangbinh.1997@gmail.com"
}

### Delete user by id

DELETE http://localhost:3000/auth/3

### Set a color

GET http://localhost:3000/auth/colors/blueashduih1323123

### Get a color

GET http://localhost:3000/auth/colors